// <auto-generated />
using AlbionMarket.Model.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbionMarket.Migrations
{
    [DbContext(typeof(AlbionContext))]
    partial class AlbionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("AlbionMarket.Model.Description", b =>
                {
                    b.Property<int>("DescriptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescriptionText");

                    b.Property<string>("Language");

                    b.Property<int>("LocalizationId");

                    b.HasKey("DescriptionId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("AlbionMarket.Model.ItemRawXml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Kind");

                    b.Property<int>("MaxStackSize");

                    b.Property<string>("ShopCategory");

                    b.Property<string>("ShopSubCategory");

                    b.Property<int>("Tier");

                    b.Property<string>("UniqueName");

                    b.Property<bool>("UnlockedToCraft");

                    b.Property<string>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AlbionMarket.Model.Localization", b =>
                {
                    b.Property<int>("LocalizationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UniqueName");

                    b.HasKey("LocalizationId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("AlbionMarket.Model.Description", b =>
                {
                    b.HasOne("AlbionMarket.Model.Localization", "Localization")
                        .WithMany("Descriptions")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
