// <auto-generated />
using System;
using AlbionMarket.Model.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbionMarket.Migrations
{
    [DbContext(typeof(LocalizationContext))]
    partial class LocalizationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("AlbionMarket.Model.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescriptionText");

                    b.Property<string>("Language");

                    b.Property<int?>("LocalizationId");

                    b.HasKey("Id");

                    b.HasIndex("LocalizationId");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("AlbionMarket.Model.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UniqueName");

                    b.HasKey("Id");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("AlbionMarket.Model.Description", b =>
                {
                    b.HasOne("AlbionMarket.Model.Localization")
                        .WithMany("Descriptions")
                        .HasForeignKey("LocalizationId");
                });
#pragma warning restore 612, 618
        }
    }
}
